### ISSUE TITLE
Convert plugin figma to html + css + js

### ISSUE THREAD

**Issue by eonist** [eonist/claude-talk-to-figma-mcp#129]
App design: https://github.com/eonist/claude-talk-to-figma-mcp/issues/90

### Todo:

- Understand the current app html+js+css structure ✅
- Convert figma design to html + js + css ✅
- figure out how to make the capsule shaped toggle component in html + css + js ✅
- figure out how to hide and show about page ✅
- Figure out best practices when storing dark mode and light mode in css and js and html ✅
- Figure out where to store the logo svg ✅ (just store it next to ui.html)
- describe how the progress ui looks like. and get pplx to draw it ✅
- use pplx to draw progress bar in Shadcn style, for light and dark mode. then design it in figma ✅
- convert figma syntax to html + css code ✅
- Figure out dark-mode / light mode auto toggle (see issue regarding figma plugin brand, it has details on how to toggle modes) (maybe just add dark mode first, then add this feature later?) ✅
- Figure out the best way to implement new html+css+js into the existing design left ask pplx. when you r ready. 👈
- wire up the auto-reconnect toggle ✅
- hock up api commands to interface

### Research: 
- capsule-shaped toggle component: https://gist.github.com/eonist/21c8a5766f3911c146429cb3f2092abc
- plugin-frontend-code-structure: https://gist.github.com/eonist/ffe4506e030e460bfb3836d122f7bd6a
- Figmas own plugin branding guideline and dark/light mode best practice: https://github.com/eonist/claude-talk-to-figma-mcp/issues/102
- Progress bar design and code: https://github.com/eonist/claude-talk-to-figma-mcp/issues/132
- Autoreconnect feature: https://github.com/eonist/claude-talk-to-figma-mcp/issues/137
- Add dark mode light mode switching mechanism in the plugin code https://github.com/eonist/claude-talk-to-figma-mcp/issues/145
- html and css for apps. generated from plugin https://gist.github.com/eonist/58fa426704a5ffb9d91bbd21e16eeb48

**Comment by eonist** [comment]
Operation progress:

![Image](https://github.com/user-attachments/assets/961e1d2e-bd5a-49da-9d4a-3e8b8461e89c)

**Comment by eonist** [comment]
1. I want to change the plugin UI 
2. here are some css: https://gist.github.com/eonist/ffe4506e030e460bfb3836d122f7bd6a?permalink_comment_id=5573312#gistcomment-5573312
3. here is some more css: https://gist.github.com/eonist/ffe4506e030e460bfb3836d122f7bd6a?permalink_comment_id=5573314#gistcomment-5573314
4. here is code for the auto-connect toggle button: https://gist.githubusercontent.com/eonist/21c8a5766f3911c146429cb3f2092abc/raw/b45c4d2268c2d4457b8f683c419f9ce32e5bcf58/capsule-shaped-toggle-component.md and animation for it: https://gist.github.com/eonist/21c8a5766f3911c146429cb3f2092abc?permalink_comment_id=5573302#gistcomment-5573302
5. here is html + css for the plugin ui: https://gist.githubusercontent.com/eonist/58fa426704a5ffb9d91bbd21e16eeb48/raw/84bbb5a32b5796702dfab13020f7bade93372d18/html%2520and%2520css%2520for%2520plugin.md and here https://gist.github.com/eonist/ffe4506e030e460bfb3836d122f7bd6a?permalink_comment_id=5576288#gistcomment-5576288 and here https://gist.github.com/eonist/ffe4506e030e460bfb3836d122f7bd6a?permalink_comment_id=5576287#gistcomment-5576287
6. here is html + css for the progress bar: https://github.com/eonist/claude-talk-to-figma-mcp/issues/132#issuecomment-2868097850 and here https://github.com/eonist/claude-talk-to-figma-mcp/issues/132#issuecomment-2868124845 and here https://github.com/eonist/claude-talk-to-figma-mcp/issues/132#issuecomment-2868125193 and here https://github.com/eonist/claude-talk-to-figma-mcp/issues/132#issuecomment-2869951592

**IMPORTANT**
(please read the provided links. if for some reason you cant access some of the links. please use terminal and curl to do so. you must read all links before you make a plan)

**Comment by eonist** [comment]
# Plugin UI Redesign Plan

After examining your project files and the provided resources, I can help you change the plugin UI. Let me outline my approach and gather any necessary clarification before we proceed.

## Current Understanding

From examining your repository, I can see you have a Figma plugin with:
- Main template (`ui-template.html`)
- Component files in the components directory
- Various CSS files (`styles.css`, `connection.css`, `tabs.css`, `progress.css`)
- JavaScript functionality in the js directory

The links you've provided contain:
1. CSS styling for light and dark modes
2. Toggle button implementation with animation
3. HTML and CSS for the main plugin UI
4. Progress bar implementation

## Proposed Implementation Approach

Here's how I plan to update your UI:

1. **Tab System**: Enhance the tab bar to toggle between "Connect" and "About" content using the provided CSS and implementation details.

2. **Auto-reconnect Toggle**: Implement the capsule-shaped toggle button for auto-connect functionality with the specified animation effects.

3. **Theme Support**: Implement both light and dark mode styling using CSS variables as defined in the provided resources.

4. **Progress Bar**: Add the progress bar component according to the designs in the GitHub issues.

5. **Connection UI**: Update the port input field, connection status display, and channel-id copy button.

## Files To Modify

Based on my analysis, I'll likely need to modify:
- `src/claude_mcp_plugin/ui-template.html`
- `src/claude_mcp_plugin/styles.css`
- `src/claude_mcp_plugin/connection.css`
- `src/claude_mcp_plugin/progress.css`
- `src/claude_mcp_plugin/components/connection-panel.html`
- `src/claude_mcp_plugin/components/tabs.html`
- `src/claude_mcp_plugin/js/ui-controller.js`
- `src/claude_mcp_plugin/js/connection.js`

## Before Starting

Before I begin implementing these changes, I'd like to clarify a few things:

1. Should the plugin automatically detect the Figma theme (light/dark) or should we implement a manual toggle?

2. Would you like me to maintain the current component-based architecture, or would you prefer a more integrated approach with fewer files?

3. Are there any specific interactions or behaviors that need special attention during this UI update?

Once you provide this information, I can proceed with developing a detailed implementation plan and then execute the changes in ACT mode.

**Comment by eonist** [comment]
QA: 

Q: Will the plugin need to run in both light and dark modes automatically based on user's Figma theme, or should we implement a manual toggle?
A:  dont implement manual toggle. we have mechanism that toggles light mode darkmode. it already works. so we just change the dark and light mode css that we currently use. 

Q: Are there any specific performance concerns with the current UI that should be addressed?
A: No

Q: Should the auto-connect toggle button be enabled by default?
A: yes (its that way now) 

Q: Are there any accessibility considerations I should keep in mind while implementing these changes?
A: no



Important notes:
- we already have progress-container. so we might just need to tweak it a little 
- i have added the logo in claude_mcp_plugin/logo.svg 
- the toggle auto-connect component will replace the current auto-connect checkbox. 
- we have theme toggle mechanism. so we just need to update the current dark / light mode styles 
- try not to edit too much javascript logic. it all works as it is suppose to. this is more about the frontend design makeover. however you can if it makes sense and doesnt break current javascript logic etc.

**Comment by eonist** [comment]
I've now updated the Claude MCP Figma plugin's UI to implement the requested designs. The changes include:

1. **Enhanced WebSocket Connection UI**:
   - Added proper "Copy channel-id" button functionality that copies the channel ID to the clipboard
   - Implemented proper "Disconnect" button functionality
   - Updated button states to be correctly enabled/disabled based on connection status
   - Added visual feedback when channel ID is copied

2. **Operation Progress UI**:
   - Added a progress bar component with percentage display
   - Implemented status messages that change based on operation state
   - Applied proper styling for both light and dark themes

3. **Theme Support**:
   - Ensured all components correctly support Figma's built-in theme system
   - Used CSS variables for consistent theming across components
   - Added automatic theme detection using Figma's theme classes

The UI now has a clean, modern design that follows Figma's styling guidelines with proper light and dark mode support. The enhanced connection UI provides clear visual feedback about the connection state, making it easier for users to understand what's happening.

The plugin is ready to be built and used with Claude Desktop's MCP server.

**Comment by eonist** [comment]
Works! but we have to do some adjustments:

Lets fix this first: Our logo is not loading. And the reason for that is that figma plugin can only read ui.html and code.js it cant import other files when loaded. so we have to embed our svg into the code. we should do this the same way as we inject our styles and js and html. with a placeholder in ui-template.html and the build files take care of injecting the svg data from the svg file


You're absolutely right about the issue with the logo not loading. Figma plugins can only read from the ui.html and code.js files, and can't load external assets like SVGs when deployed. Let's look at how we can fix this.

Based on your explanation, we need to:
1. Embed the SVG data directly in our HTML 
2. Use a placeholder in the ui-template.html file
3. Have the build process inject the actual SVG content from the logo.svg file

This is a smart approach since it maintains separation of concerns during development but ensures everything is properly packaged at build time.

Here's what I propose:

1. Modify the header.html file to use a placeholder for the SVG content instead of referencing an external file
2. Add a new placeholder in ui-template.html for the SVG data
3. Update the build script to read the logo.svg file and inject its contents into the placeholder

This way, during development we can still work with the SVG file separately, but at build time it gets embedded directly into the HTML.

Would you like me to outline the specific changes needed to each file? If so, I can prepare the changes for implementation once we switch to Act mode.

**Comment by eonist** [comment]
I guess we have to put the placeholder in the header.html? i guess an alternative is also to just put the raw svg code into the header.html. what do you think?


Both approaches have their merits:

**Option 1: Using a placeholder in header.html**
- Keeps header.html cleaner and easier to read
- Better separation of concerns (SVG maintained separately)
- Makes it easier to update the logo in the future
- But adds complexity to the build process

**Option 2: Embedding raw SVG directly in header.html**
- Simpler implementation - no need to modify build scripts
- Guarantees the SVG is included (no chance of placeholder replacement failing)
- One less moving part in the build system
- Works immediately without any additional changes

After looking at the SVG content, I think embedding directly is probably the more practical option in this case. The SVG is relatively compact (under 20 lines) and isn't overly complex. Since it's only used in one place, embedding it directly in header.html would be straightforward and avoid adding complexity to the build process.

If you agree, we can update the header.html file to replace:
```html
<img src="logo.svg" alt="Conduit Logo" class="header-logo-image">
```

with the complete SVG element (properly styled with the header-logo-image class). This would be the quickest solution that ensures the logo displays correctly.

Would you like to proceed with embedding the SVG directly in the header.html file? If so, I'll prepare the changes for when we switch to Act mode.

**Comment by eonist** [comment]
I've successfully embedded the SVG logo directly into the header.html file as requested. 

Here's what I did:
1. Read the SVG content from the logo.svg file
2. Integrated the full SVG directly into the header.html markup
3. Maintained the proper class "header-logo-image" for consistent styling
4. Preserved the existing HTML structure for the header component

Benefits of this approach:
- Eliminates the need for a separate logo.svg file
- Ensures the logo loads immediately with the UI (no separate file reference)
- Allows for CSS styling to be applied directly to the SVG
- Fits within the existing build process without modifications

The logo will now be properly displayed in the header of the Figma plugin UI, maintaining the same appearance as before but with a more efficient implementation. The existing CSS in connection.css already handles the proper sizing and positioning of the SVG.

**Comment by eonist** [comment]
I understand what needs to be done. Looking at the images and the specifications from your initial links, we need to update the CSS to use your custom color scheme instead of Figma's native theme colors.

Here's my plan for the CSS modifications:

### 1. Background Colors
- Dark mode: Replace with #121212 or #1A1A1A for main background
- Light mode: Replace with #F5F5F5 for main background

### 2. Button Colors
For dark mode:
- Connect button (primary): White (#FFFFFF) background with black text
- Copy channel-id and Disconnect buttons (secondary): #3C3C3C background with white text

For light mode:
- Connect button (primary): Dark (#1A1F29) background with white text
- Copy channel-id and Disconnect buttons (secondary): Light gray background with dark text

### 3. Input Field (Port Text Field)
- Dark mode: #2C2C2C background with light text
- Light mode: Light background (#F0F0F0) with dark text

### 4. Implementation Approach
1. Modify the styles.css file to:
   - Add custom CSS variables for our theme instead of using Figma's native variables
   - Create both dark and light mode color schemes

2. Update connection.css to ensure all component-specific styles use our custom variables

3. Potentially add a theme toggle mechanism if needed

This will require overriding Figma's default color system with our own custom variables, but will give us the exact look from the initial specifications.

Would you like me to proceed with these changes when we switch to Act mode? Any adjustments to the color palette or approach before I implement these changes?

**Comment by eonist** [comment]
Now I've fixed the button styling to ensure they properly respect theme changes! The changes include:

1. Added explicit styling for the button IDs (`#btn-connect`, `#btn-copy-channel`, and `#btn-disconnect`) to ensure they directly use our theme variables
2. Added smooth transition effects to improve the visual appearance when switching between themes
3. Made sure the button states (hover, disabled) are properly themed in both light and dark modes
4. Rebuilt the plugin to deploy these changes

The connect, copy channel, and disconnect buttons will now properly change appearance when switching between light and dark themes. In dark mode:

- Connect button: White background with black text
- Secondary buttons: Dark gray background with white text

In light mode:

- Connect button: Dark blue background with white text
- Secondary buttons: Light gray background with dark text

All buttons now have proper hover states and transitions to make the theme switching look smooth and professional.

**Comment by eonist** [comment]
I've successfully updated the plugin UI to ensure all buttons properly respect theme changes. The issue was that while the buttons were using the correct classes (primary and secondary), they needed explicit targeting for proper theme application.

### Changes Made:

1. Added direct ID targeting for each button:
   ```css
   /* Ensure specific button IDs properly apply theme colors */
   #btn-connect {
     background-color: var(--button-primary-bg);
     color: var(--button-primary-text);
   }

   #btn-copy-channel, #btn-disconnect {
     background-color: var(--button-secondary-bg);
     color: var(--button-secondary-text);
   }
   ```

2. Added smooth transitions to button theme changes:
   ```css
   button.primary, button.secondary {
     transition: background-color 0.3s ease, color 0.3s ease;
   }
   ```

3. Added hover states that properly respect theme variables

All three buttons (Connect, Copy channel-id, and Disconnect) now correctly update their styling when switching between light and dark themes, with smooth transitions and proper contrast in both modes.

**Comment by eonist** [comment]
I've updated both buttons to match your specifications:

1. For the Disconnect Button:
   - Changed its class from "secondary" to "primary" in HTML
   - Updated CSS to ensure both Connect and Disconnect buttons share the same primary styling
   - Now matches the Connect button's appearance in both light and dark modes

2. For the Copy Channel ID Button:
   - Added specific styling to ensure it properly uses the secondary styling
   - Made it full width by adding `width: 100%` for better visual appearance
   - Maintains the proper secondary button styling in both theme modes

All buttons now properly respect theme changes and have appropriate hover states. The plugin has been successfully rebuilt with these updates, ensuring consistent appearance across all UI elements.

The styling now correctly implements:
- Primary buttons (Connect, Disconnect): White with black text in dark mode, dark blue with white text in light mode
- Secondary button (Copy Channel ID): Dark gray with white text in dark mode, light gray with dark text in light mode

**Comment by eonist** [comment]
I understand the issues with the Copy Channel ID button. Let me outline a plan to fix them:

1. The button now fills the entire width of the view, which it didn't before
   - I added `width: 100%` to the `#btn-copy-channel` selector in my CSS changes
   - I need to remove this property to restore the button to its original width

2. The styling is not correct
   - I need to ensure the button properly uses the secondary button styling
   - I need to make sure the button respects both dark and light theme changes

The changes will be simple CSS modifications to the `styles.css` file. I'll remove the full width setting while keeping the proper theme color variables so the button displays correctly.

To make these changes, I'll need to be in Act Mode. Would you like to toggle to Act Mode so I can implement these fixes?

**Comment by eonist** [comment]
I've successfully fixed the issues with the Copy Channel ID button:

1. Removed the `width: 100%` property from the `#btn-copy-channel` CSS selector that was making the button fill the entire width of the view
2. Maintained the proper secondary button styling with:
   - Correct background color variable (`var(--button-secondary-bg)`)
   - Correct text color variable (`var(--button-secondary-text)`)
   - Proper hover state styling

The button should now display at its natural width instead of filling the entire container, while still maintaining the appropriate styling for both light and dark themes.

The Disconnect button remains styled correctly as a primary button (matching the Connect button), as requested previously.

Although there was an issue capturing the output of the build command, the command itself ran successfully according to the error message, so the plugin should be updated with these style changes.

**Comment by eonist** [comment]
I see the issue now. Looking at the HTML and CSS, I found that the "Copy channel-id" button is using the "secondary" class, while the "Connect" and "Disconnect" buttons are using the "primary" class. This is why they don't match in style.

To fix this according to your specifications, I need to:

1. Change the class of the "Copy channel-id" button from "secondary" to "primary" in the `connection-panel.html` file

The current HTML for the button is:
```html
<button id="btn-copy-channel" class="secondary" disabled>
  Copy channel-id
</button>
```

It should be changed to:
```html
<button id="btn-copy-channel" class="primary" disabled>
  Copy channel-id
</button>
```

I'll need to be in Act Mode to make this change. Would you like to toggle to Act Mode so I can implement this fix?

**Comment by eonist** [comment]
I've successfully updated the Copy Channel ID button to match the Connect and Disconnect buttons in style:

1. Changed the "Copy channel-id" button's class from "secondary" to "primary" in the connection-panel.html file
2. Updated the CSS in styles.css to ensure all three buttons share the same styling by:
   - Adding #btn-copy-channel to the same selector group as #btn-connect and #btn-disconnect
   - Setting all buttons to use the primary button variables for colors and hover states
   - Removing the separate styling rules that were making the Copy Channel ID button use the secondary style

Now all three buttons will have the same appearance:
- In dark mode: white background with black text
- In light mode: dark blue background with white text
- Consistent hover effects for all buttons
- Proper disabled state styling when applicable

These changes maintain the width fixes we made earlier (removing the full-width style) while ensuring visual consistency across all buttons as requested.

The build command has executed successfully, so the Figma plugin should now display the updated styling.

**Comment by eonist** [comment]
Thank you for providing both images! Now I clearly understand what you're looking to achieve.

Looking at the second image with the dark status box, I can see several differences in spacing and padding compared to the current design:

1. More horizontal padding from the edges of the plugin container
2. Better spacing between form elements (port input, toggle, status box, buttons)
3. Improved internal padding within the status box
4. More consistent spacing throughout the interface

To achieve this cleaner layout from the second image, I'll need to:
1. Adjust the padding in the `.plugin-container` class
2. Update spacing between form elements
3. Ensure proper padding inside the status box
4. Review margins for all UI components

I'll need to be in Act Mode to implement these CSS changes. Would you like to toggle to Act Mode so I can make these adjustments to match the padding and spacing shown in the second image?

**Comment by eonist** [comment]
I've reduced the space between the header and tab bar by changing the header's bottom margin from 24px to 12px in the connection.css file. 

This adjustment creates more consistent spacing throughout the UI with approximately 12px spacing between elements, matching the design in the reference image. Now all the major sections of the plugin have similar spacing between them:

1. Header to tabs: 12px (previously 24px)
2. Tabs to first form element: 12px
3. Between form elements: 12px
4. Status area spacing: 12px top and bottom

The overall vertical rhythm is now more consistent and compact, creating a cleaner interface that matches the reference image. The elements flow better visually with equal breathing room between components rather than having an unusually large gap between the header and tabs.

**Comment by eonist** [comment]
Based on my analysis of the files, I understand what changes need to be made to the app logo. Here's my plan:

## Current State
- The logo SVG in header.html currently includes both a background rectangle and the actual logo shape
- The current background is hardcoded with fill="#D9D9D9" 
- The SVG viewBox is 600x600

## Planned Changes

1. **Logo Container Styling**:
   - Modify the `.header-logo` class to be 40x40px instead of its current size
   - Add 6px corner radius to the container 
   - Set background colors via CSS:
     - Light mode: #1A1F29 (dark blue-gray)
     - Dark mode: #F0F0F0 (light gray)

2. **SVG Content**:
   - Replace the current SVG in header.html with the content from logo_no_bg.svg
   - Ensure the SVG is properly centered within the 40x40px container

3. **CSS Implementation**:
   - Add CSS rules for the logo container that respond to the theme
   - Use existing theme variables for consistency

Once you're satisfied with this plan, please toggle to Act mode so I can implement these changes.

**Comment by eonist** [comment]
I'll create the HTML and CSS that would replicate the UI shown in the image. The interface appears to be for the Conduit MCP plugin with a connection panel.

Here's how you could implement this UI:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Conduit MCP Plugin</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>Conduit MCP plugin</h1>
        </header>
        
        <div class="app-header">
            <div class="logo-container">
                <div class="logo"></div>
                <div class="app-info">
                    <h2>Conduit</h2>
                    <p>Design at the speed of thought</p>
                </div>
            </div>
        </div>
        
        <div class="tabs">
            <div class="tab active">Connection</div>
            <div class="tab">About</div>
        </div>
        
        <div class="connection-form">
            <div class="form-group">
                <label for="websocket-port">Websocket-port:</label>
                <input type="text" id="websocket-port" value="3055">
                <button class="connect-btn">Connect</button>
            </div>
            
            <div class="toggle-group">
                <label class="toggle">
                    <input type="checkbox" checked>
                    <span class="slider round"></span>
                </label>
                <span class="toggle-label">Auto connect to server</span>
            </div>
            
            <div class="status-box">
                <p>Connected to server on port "3055" in channel: "eveycv75"</p>
            </div>
            
            <button class="copy-btn">Copy channel-id</button>
        </div>
    </div>
</body>
</html>
```

```css
:root {
    --bg-color: #121212;
    --card-bg: #1e1e1e;
    --text-color: #ffffff;
    --text-secondary: #a0a0a0;
    --accent-color: #ffffff;
    --border-color: #333333;
    --button-bg: #ffffff;
    --button-text: #000000;
    --input-bg: #2a2a2a;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}

body {
    background-color: var(--bg-color);
    color: var(--text-color);
    padding: 20px;
}

.container {
    max-width: 650px;
    margin: 0 auto;
}

header h1 {
    font-size: 20px;
    color: var(--text-secondary);
    margin-bottom: 20px;
    font-weight: normal;
}

.app-header {
    margin-bottom: 30px;
}

.logo-container {
    display: flex;
    align-items: center;
    gap: 15px;
}

.logo {
    width: 60px;
    height: 60px;
    background-color: var(--card-bg);
    border-radius: 10px;
}

.app-info h2 {
    font-size: 28px;
    margin-bottom: 5px;
}

.app-info p {
    color: var(--text-secondary);
    font-size: 16px;
}

.tabs {
    display: flex;
    margin-bottom: 30px;
    border-bottom: 1px solid var(--border-color);
}

.tab {
    padding: 10px 0;
    margin-right: 30px;
    font-size: 18px;
    cursor: pointer;
}

.tab.active {
    color: var(--accent-color);
    border-bottom: 2px solid var(--accent-color);
}

.connection-form {
    display: flex;
    flex-direction: column;
    gap: 20px;
}

.form-group {
    display: flex;
    flex-direction: column;
    gap: 10px;
}

label {
    font-size: 16px;
    margin-bottom: 5px;
}

input[type="text"] {
    background-color: var(--input-bg);
    border: none;
    border-radius: 5px;
    padding: 15px;
    color: var(--text-color);
    font-size: 16px;
    width: 100%;
    margin-bottom: 10px;
}

.connect-btn {
    background-color: var(--button-bg);
    color: var(--button-text);
    border: none;
    border-radius: 5px;
    padding: 15px 20px;
    font-size: 16px;
    font-weight: bold;
    cursor: pointer;
    align-self: flex-end;
    width: 150px;
}

.toggle-group {
    display: flex;
    align-items: center;
    gap: 15px;
}

.toggle {
    position: relative;
    display: inline-block;
    width: 50px;
    height: 24px;
}

.toggle input {
    opacity: 0;
    width: 0;
    height: 0;
}

.slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: var(--input-bg);
    transition: .4s;
}

.slider:before {
    position: absolute;
    content: "";
    height: 20px;
    width: 20px;
    left: 2px;
    bottom: 2px;
    background-color: white;
    transition: .4s;
}

input:checked + .slider {
    background-color: var(--accent-color);
}

input:checked + .slider:before {
    transform: translateX(26px);
}

.slider.round {
    border-radius: 24px;
}

.slider.round:before {
    border-radius: 50%;
}

.toggle-label {
    color: var(--text-secondary);
}

.status-box {
    background-color: var(--card-bg);
    border-radius: 5px;
    padding: 20px;
}

.status-box p {
    color: var(--text-color);
}

.copy-btn {
    background-color: transparent;
    color: var(--text-color);
    border: 1px solid var(--border-color);
    border-radius: 5px;
    padding: 15px 20px;
    font-size: 16px;
    cursor: pointer;
    width: fit-content;
}
```

This code creates a dark-themed UI that matches the image, with:

1. A header showing "Conduit MCP plugin"
2. The Conduit logo and tagline
3. Navigation tabs for "Connection" and "About"
4. A websocket port input field set to "3055"
5. A "Connect" button
6. A toggle switch for "Auto connect to server"
7. A status box showing the connection information
8. A "Copy channel-id" button

The CSS uses CSS variables for consistent theming and implements the dark mode appearance shown in the image. The layout is responsive and maintains the visual hierarchy seen in the interface.

Sources
[1] DarkMode_final.jpg https://pplx-res.cloudinary.com/image/upload/v1746978877/user_uploads/60313916/59ea1723-5a5d-446e-a4b4-2927f7ace580/DarkMode_final.jpg
