### ISSUE TITLE
App UI tweaks

### ISSUE THREAD

**Issue by eonist** [eonist/claude-talk-to-figma-mcp#159]
- App Logo 
    - Logo should be smaller use size from figma design
    - logo BG should be set by css (black for light mode, white for dark mode)
    - provide logo with only content no rounded frame. 
- Toggle component should be:  ✅
    -  light mode: button should be white for when disabled.  black when active  ✅
    - darkmde: button should be black for when disabled. white when active  ✅
    - the toggle component background stays the same  ✅
- status textfield should be ✅
    - very subtly green tinted when connected. its too green now ✅
    - and same for disconnected with subtle red✅
    - or drop green and red. instead just use the design we made in figma. ✅
         - slight bg color for dark and light mode. ✅
         - and no color for text. just the same as in figma specs. ✅
     - tweak the auto connect status text a bit. right now its a bit ambiguous. ask gpt for better text
     - when status text changes. could we animate the change. so its less abrupt. 
- the tabbar: ✅
     - the inactive button should have no background color the active button should keep its current background color✅
    - the container of the tabbar should be flush with the buttons inside. no padding. ✅
         - for dark mode the background in the container should have the same color as the bg-color we use in the app 141414. ✅
         - for light mode the background in the container should have this background color: F2F2F2✅
         -  the container should have a dropshaddow ✅
               - for dark mode that is subtly white. so very weak white. nearly black.✅
               -  for light mode the dropshaddow should be nearly white. weak black. ✅
         - keep the rounded corners as is, no other styling needed.✅
-  we need to remove the disconnect button.  ✅
    -  move this functionality into the connect button ✅
    - when disconnected the connect button should show the text: "Connect"✅
    - when connected. the contact button should show the text: "Disconnect"✅
    - when auto-connect is toggled on. The entire button should be disabled. currently it's only disabled if auto connect is on. and we are actually connected. it should be disabled if auto connect is on. and not be dependant on actual connection  status. ✅
- when we toggle the auto-connect to on. the auto connect flow should be triggered.when we toggle to off it should stop✅
- The copy channel id button: ✅
    - background color is currently muted. it should be the same style as connect button when it is enabled. ✅
    - When we copy the channel id by pressing the copy channel id button I want to: ✅
        - send ui notification to figma. -> Copied channel id "insert channel id here" . ✅
            - this is similar to  when we connect. we get a notification. reuse this code etc✅

**Comment by eonist** [comment]
Based on your requirements for the tabbar, I need to make several CSS changes to the existing implementation in the Figma plugin. After reviewing the current code, here's what I'll need to modify:

1. For the tab buttons:
   - Remove the background color from inactive buttons
   - Keep the current background color for active buttons

2. For the tabbar container:
   - Remove the padding (`padding: 4px 16px;`) to make it flush with the buttons
   - Ensure dark mode background is #141414 (it already is)
   - Ensure light mode background is #F2F2F2 (it already is)
   - Add a drop shadow:
     - Dark mode: Very subtle white shadow (nearly black)
     - Light mode: Weak black shadow (nearly white)
   - Keep the existing rounded corners

Here's my plan to update the `tabs.css` file:

```css
/* Tab colors - No changes needed to these variables */
:root {
  --tab-border-color: #333333;
  --tab-text-color: #8C8C8C;
  --tab-active-text: #FFFFFF;
  --tab-active-border: #FFFFFF;
  --tab-active-bg: #171717;
  --tab-inactive-bg: #141414;
}

/* Light theme tab colors - No changes needed */
body.theme-light {
  --tab-border-color: #DDDDDD;
  --tab-text-color: #737373;
  --tab-active-text: #0F1729;
  --tab-active-border: #0F1729;
  --tab-active-bg: #FFFFFF;
  --tab-inactive-bg: #F2F2F2;
}

/* Update the tabs container */
.tabs {
  display: flex;
  border-bottom: 1px solid var(--tab-border-color);
  margin-bottom: 12px;
  margin-left: 16px;
  margin-right: 16px;
  /* Remove the padding */
  background-color: var(--tab-inactive-bg);
  border-radius: 8px;
  transition: border-color 0.3s ease;
  /* Add drop shadow based on theme */
  box-shadow: 0px 2px 4px rgba(255, 255, 255, 0.05); /* Dark mode shadow */
}

/* Add light mode shadow */
body.theme-light .tabs {
  box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.05); /* Light mode shadow */
}

/* Update the tab styling */
.tab {
  flex: 1;
  padding: 10px 0;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  text-align: center;
  color: var(--tab-text-color);
  transition: color 0.3s ease, background-color 0.3s ease, border-color 0.3s ease;
  border-radius: 6px;
  /* No background for inactive tabs - remove or set to transparent */
  background-color: transparent;
}

/* Keep active tab styling */
.tab.active {
  background-color: var(--tab-active-bg);
  color: var(--tab-active-text);
  font-weight: 600;
  box-shadow: 0px 1px 2px 0px rgba(0, 0, 0, 0.06);
}

/* No changes needed below */
.tab-content {
  display: none;
}
.tab-content.active {
  display: block;
}
```

Would you like me to proceed with these changes? If you have any adjustments to the plan before I implement it, please let me know.
